name: Angular Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select Branch"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - main
        
      env:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - india
          - uk

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Selected Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      #  Build based on environment
      - name: Build Angular App
        run: |
          echo "Selected ENV: ${{ github.event.inputs.env }}"
          
          # Map dev → development (Angular default
          if [ "${{ github.event.inputs.env }}" = "dev" ]; then
            CONFIG=development
          else
            CONFIG=${{ github.event.inputs.env }}
          fi

          echo "Using Angular config: $CONFIG"
          npm run build -- --configuration=$CONFIG --base-href=/GitHub-actions/angular/

      - name: Show Build Output
        run: |
          echo "Dist files:"
          ls -R dist

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      #  Stop Apache
      - name: Stop Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl stop apache2"

      #  Copy Build Files (IMPORTANT FIX)
      - name: Copy Build Files to EC2
        run: |
          scp -r dist/*/browser/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/angular-build

      #  Deploy + Start Apache
      - name: Deploy and Start Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            sudo rm -rf /var/www/html/GitHub-actions/angular/*
            
            sudo mv /tmp/angular-build/* /var/www/html/GitHub-actions/angular/
            sudo systemctl start apache2
          "
